---
apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-config
data:
  CART_HOST: "cart"
  USER_HOST: "users"
  AMQP_HOST: "rabbitmq"
---
apiVersion: v1
kind: Pod
metadata:
  name: payment
  labels:
    name: payment
    tier: app
spec:
  containers:
  - name: payment
    imagePullPolicy: Always
    image: naveen2809/payment:v1
    envFrom:
    - configMapRef:
        name: payment-config
---
apiVersion: v1
kind: Service
metadata:
  name: payment
spec:
  selector:
    name: payment
    tier: app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080