apiVersion: v1
kind: Pod
metadata:
  name: ratings
  labels:
    name: ratings
    tier: app
spec:
  containers:
  - name: ratings
    image: naveen2809/ratings:v1
---
apiVersion: v1
kind: Service
metadata:
  name: ratings
spec:
  selector:
    name: ratings
    tier: app
  ports:
  - port: 8080
    targetPort: 8080