---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
data:
  REDIS_HOST: "redis"
  MONGO_URL : "mongodb://mongo:27017/users"
---
apiVersion: v1
kind: Pod
metadata:
  name: user
  labels:
    name: user
    tier: app
spec:
  containers:
  - name: user
    imagePullPolicy: Always
    image: naveen2809/user:k8s
---
apiVersion: v1
kind: Service
metadata:
  name: users
spec:
  selector:
    name: user
    tier: app
  ports:
  - port: 8080
    targetPort: 8080